lesson_8/geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path(r'register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    ]

lesson_8/geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp


app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<pk>/', basketapp.basket_add, name='add'),
    path('remove/<pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<pk>/<quantity>/', basketapp.basket_edit, name='edit'),
    ]

lesson_8/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('mainapp.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', include(('adminapp.urls', 'adminapp'), namespace='admin')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lesson_8/geekshop/mainapp/urls.py
from django.urls import path
from django.conf.urls import url
import mainapp.views as mainapp


urlpatterns = [
	path('', mainapp.main, name='main'),
	path('catalog/', mainapp.catalog, name='catalog'),
	path('contact/', mainapp.contact, name='contact'),
	path('catalog/<pk>/', mainapp.catalog, name='catalog'),
	path('product/<pk>', mainapp.product, name='product'),
]

lesson_8/geekshop/mainapp/models.py
from django.db import models


# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='кратко', max_length=256, blank=True)
    description = models.TextField(verbose_name='подробно', blank=True)
    isbn = models.CharField(verbose_name='ISBN', max_length=32, blank=True)
    author = models.CharField(verbose_name='автор', max_length=64, blank=True)
    price = models.DecimalField(verbose_name='цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='склад', default=0)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

lesson_8/geekshop/mainapp/views.py
from django.http import HttpResponseBadRequest
from django.shortcuts import render
from basketapp.models import Basket
from .models import ProductCategory, Product
from django.shortcuts import get_object_or_404
import random

# Create your views here.
links_menu = [
    {'href': 'main', 'name': 'главная'},
    {'href': 'catalog', 'name': 'магазин'},
    {'href': 'contact', 'name': 'контакты'},
]

def getBasket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def getHotProduct():
    products = Product.objects.all()
    return random.sample(list(products), 4)


def main(request):
    hot_product = getHotProduct()
    content = {
        'title': 'главная',
        'links_menu': links_menu,
        'hot_product': hot_product,
    }
    return render(request, 'mainapp/index.html', content)


def catalog(request, pk=None):
    title = 'магазин'
    catalog_menu = ProductCategory.objects.all()
    basket = getBasket(request.user)

    if pk:
        if pk == '0':
            category = {'name': 'все'}
            products = Product.objects.all().order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')

        content = {
            'title': title,
            'links_menu': links_menu,
            'catalog_menu': catalog_menu,
            'category': category,
            'products': products,
        }

        return render(request, 'mainapp/catalog.html', content)

    products = Product.objects.all()

    content = {
        'title': title,
        'links_menu': links_menu,
        'catalog_menu': catalog_menu,
        'products': products,
        'category': {'name': 'все'},
        'basket': basket,
    }
    return render(request, 'mainapp/catalog.html', content)


def product(request, pk=None):
    basket = getBasket(request.user)
    title = get_object_or_404(Product, id=pk).name
    product_ = get_object_or_404(Product, id=pk)
    content = {
        'title': title,
        'links_menu': links_menu,
        'product': product_,
        'basket': basket,
    }

    return render(request, 'mainapp/product.html', content)


def contact(request):
    content = {
        'title': 'контакты',
        'links_menu': links_menu,
    }
    return render(request, 'mainapp/contact.html', content)

lesson_8/geekshop/mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/master.html' %}
{% load staticfiles %}

{% block content %}
    <section>
        <div class="basket-notice">
            {% include 'mainapp/includes/inc_basket.html' %}
        </div>

        <h1>Каталог товаров</h1>

        {% include 'mainapp/includes/inc_categories_menu.html' %}

        <div class="block">
            {% for product in products %}
                <p class="storegrid">
                    <a href="{% url 'product' product.pk %}">
                        <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                        <br>
                        <span>{{ product.name|capfirst }}</span>
                    </a>
                </p>
            {% endfor %}
        </div>
    </section>
{% endblock %}

lesson_8/geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/master.html' %}
{% load staticfiles %}

{% block content %}
    <section class="contact">
        <h1>Контакты</h1>
        <form action="/contact/"><!--method="post"-->
            <fieldset>
                <legend>Напишите нам</legend>
                <label for="name">Ваше имя:</label>
                <input id="name" type="text" size="30" placeholder="Иван Иванов"><br>
                <label for="mail">Ваш email:</label>
                <input id="mail" type="email" size="30" placeholder="ivanov@yandex.ru"><br>
                <label for="subject">Тема:</label>
                <select id="subject">
                    <option>Подарки</option>
                    <option>Оплата</option>
                    <option>Доставка</option>
                    <option>Возврат</option>
                    <option>Прочее</option>
                </select><br>
                <label for="usertext">Ваше сообщение:</label><br>
                <textarea id="usertext" cols="43" rows="4"></textarea>
                <button type="submit">Отправить</button>
            </fieldset>
        </form>
        <article class="address">
            <h3>Адрес</h3>
            <span id="longdesc">
                450000, г. Уфа, ул. Ленина, 1<br>
                Email: orelly@yandex.ru<br>
                Телефон: +7 (347) 2552255<br>
            </span>
        </article>
        <span class="stub" id="map">
                    <script type="text/javascript" charset="utf-8" async
                            src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A043acd2ad3d076177e526e4d2983989155aec0669b511e9a167aa6b66969b728&amp;width=100%25&amp;height=360&amp;lang=ru_RU&amp;scroll=true"></script>
                </span>
    </section>
{% endblock %}

lesson_8/geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/master.html' %}
{% load staticfiles %}

{% block content %}
    <section>
        <div class="basket-notice">
            <span>
                <a href="{% url 'basket:view' %}">
                    &#128722; Ваши покупки
                </a>
            </span>
        </div>
        <h1>Бестселлеры O'Reilly</h1>
        <h2>Добро пожаловать в мир книг издательства O'Reilly</h2>
        <p>
            O'Reilly — одно из крупнейших издательств — начало свою деятельность в 1984 году
            с создания руководств для вендоров операционной системы Unix. На сегодняшний день ассортимент
            наименований этого издательства весьма широк: от книг для любителей цифровой фотографии до изданий,
            предназначенных профессиональным разработчикам программного обеспечения. Книги издательства O'Reilly
            отличаются достоверностью, полезны и интересны.
        </p>

        <h2>Горячие предложения</h2>
        <div class="block">
            {% for product in hot_product %}
                <p class="storegrid">
                    <a href="{% url 'product' product.pk %}"><img src="/media/{{ product.image }}" alt=""></a>
                    <br>
                    <span>{{ product.name|capfirst }}</span>
                </p>
            {% endfor %}
        </div>

    </section>
{% endblock %}

lesson_8/geekshop/mainapp/templates/mainapp/master.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static '/css/normalize.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    {% endblock %}
    {% block pagecss %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="container">
    {% block header %}
        <header>
            <nav>
                <a id="logo" href="/"><img src="{% static 'img/logo_oreilly.png' %}"></a>
                {% include 'mainapp/includes/inc_header_menu.html' %}
            </nav>
        </header>
    {% endblock %}
    {% block content %}
    {% endblock %}
    {% block footer %}
        <footer>
            <p>&#169; {%  now "Y" %}</p>
        </footer>
    {% endblock %}
</div>
</body>
</html>

lesson_8/geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/master.html' %}
{% load staticfiles %}

{% block content %}
    <section class="products">
        <div class="basket-notice">
            {% include 'mainapp/includes/inc_basket.html' %}
        </div>
        <h1>{{ product.name|capfirst }}</h1>
        <h3>Автор: <em>{{ product.author|capfirst }}</em></h3>
        <div class="img-block">
            <div class="img-container"><img src="/media/{{ product.image }}" alt="Простой Python"></div>
            <p id="shortdesc">
                {{ product.short_desc|capfirst }}
            </p>
            <p id="shortdesc">
                Стоимость: <span class="price">Q{{ product.price }}</span>
            </p>
            <form action="{% url 'basket:add' product.pk %}">
                <button>Купить</button>
            </form>
        </div>
        <h3 class="stub">Характеристики:</h3>
        <ul>
            <li>ISBN: {{ product.isbn|capfirst }}</li>
            <li>Остаток на складе: {{ product.quantity|capfirst }} шт.</li>
        </ul>
        <h3>Подробное описание:</h3>
        <p id="longdesc">
            {{ product.description|capfirst }}
        </p>
    </section>
{% endblock %}