lesson_8/geekshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<pk>/', adminapp.user_delete, name='user_delete'),
    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<pk>/', adminapp.category_delete, name='category_delete'),
    path('products/create/category/<pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<pk>/', adminapp.products, name='products'),
    path('products/read/<pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<pk>/', adminapp.product_delete, name='product_delete'),
]

lesson_8/geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path(r'register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    ]

lesson_8/geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp


app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<pk>/', basketapp.basket_add, name='add'),
    path('remove/<pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<pk>/<quantity>/', basketapp.basket_edit, name='edit'),
    ]

lesson_8/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('mainapp.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', include(('adminapp.urls', 'adminapp'), namespace='admin')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lesson_8/geekshop/mainapp/urls.py
from django.urls import path
from django.conf.urls import url
import mainapp.views as mainapp


urlpatterns = [
	path('', mainapp.main, name='main'),
	path('catalog/', mainapp.catalog, name='catalog'),
	path('contact/', mainapp.contact, name='contact'),
	path('catalog/<pk>/', mainapp.catalog, name='catalog'),
	path('product/<pk>', mainapp.product, name='product'),
]

lesson_8/geekshop/mainapp/models.py
from django.db import models


# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='кратко', max_length=256, blank=True)
    description = models.TextField(verbose_name='подробно', blank=True)
    isbn = models.CharField(verbose_name='ISBN', max_length=32, blank=True)
    author = models.CharField(verbose_name='автор', max_length=64, blank=True)
    price = models.DecimalField(verbose_name='цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='склад', default=0)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

lesson_8/geekshop/mainapp/views.py
from django.http import HttpResponseBadRequest
from django.shortcuts import render
from basketapp.models import Basket
from .models import ProductCategory, Product
from django.shortcuts import get_object_or_404
import random

# Create your views here.
links_menu = [
    {'href': 'main', 'name': 'главная'},
    {'href': 'catalog', 'name': 'магазин'},
    {'href': 'contact', 'name': 'контакты'},
]

def getBasket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def getHotProduct():
    products = Product.objects.all()
    return random.sample(list(products), 4)


def main(request):
    hot_product = getHotProduct()
    content = {
        'title': 'главная',
        'links_menu': links_menu,
        'hot_product': hot_product,
    }
    return render(request, 'mainapp/index.html', content)


def catalog(request, pk=None):
    title = 'магазин'
    catalog_menu = ProductCategory.objects.all()
    basket = getBasket(request.user)

    if pk:
        if pk == '0':
            category = {'name': 'все'}
            products = Product.objects.all().order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')

        content = {
            'title': title,
            'links_menu': links_menu,
            'catalog_menu': catalog_menu,
            'category': category,
            'products': products,
        }

        return render(request, 'mainapp/catalog.html', content)

    products = Product.objects.all()

    content = {
        'title': title,
        'links_menu': links_menu,
        'catalog_menu': catalog_menu,
        'products': products,
        'category': {'name': 'все'},
        'basket': basket,
    }
    return render(request, 'mainapp/catalog.html', content)


def product(request, pk=None):
    basket = getBasket(request.user)
    title = get_object_or_404(Product, id=pk).name
    product_ = get_object_or_404(Product, id=pk)
    content = {
        'title': title,
        'links_menu': links_menu,
        'product': product_,
        'basket': basket,
    }

    return render(request, 'mainapp/product.html', content)


def contact(request):
    content = {
        'title': 'контакты',
        'links_menu': links_menu,
    }
    return render(request, 'mainapp/contact.html', content)

lesson_8/geekshop/mainapp/templates/mainapp/includes/inc_basket.html
<span>
    {% if basket %}
        <a href="{% url 'basket:view' %}">
        &#128722;
        Товаров в корзине: {{ basket.0.total_quantity }}
        общей стоимостью: Q{{ basket.0.total_cost|floatformat:2 }}
        </a>
    {% endif %}
</span>

lesson_8/geekshop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
    <li>
        выбрать:
    </li>
    <li>
        <a href="{% url 'catalog' 0 %}"
           class="{% if request.resolver_match.kwargs.pk == '0' %}
                  active
                  {% endif %}">
            всё
        </a>
    </li>
    {% for link in catalog_menu %}
        <li>
            <a href="{% url 'catalog' link.pk %}"
               class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
                        active
                      {% endif %}">
                {{ link.description }}
            </a>
        </li>
    {% endfor %}
</ul>

lesson_8/geekshop/mainapp/templates/mainapp/includes/inc_header_menu.html
<ul>
    {% for link in links_menu %}
        <li>
            <a href="{% url link.href %}"
               class="{% if request.resolver_match.url_name == link.href %}selected{% endif %}">
                {{ link.name }}
            </a>
        </li>
    {% endfor %}

    {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:edit' %}">
                &#9786;{{ user.first_name|default:'Пользователь' }}
            </a>
        </li>
    {% endif %}

    {% if user.is_superuser %}
    <li>
        <a href="{% url 'admin:users' %}">управление</a>
    </li>
    {% endif %}

    <li>
        {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">выйти</a>
        {% else %}
            <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </li>

</ul>